name: publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup python3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install poetry
        run: python -m pip install poetry

      - name: Build package
        run: poetry build

      - name: Mint token
        id: mint
        uses: tschm/token-mint-action@v1.0.2

      - name: Publish to PyPI
        run: poetry publish -u __token__ -p '${{ steps.mint.outputs.api-token }}'
